name: 3hgj_merge
description: A sample dartemis application
dependencies:
  browser: any
  canvas_query: any
  dartemis_toolbox: any
  gamedev_helpers:
    git: https://github.com/denniskaselow/gamedev_helpers
#    path: ../gamedev_helpers
  lawndart: any
  dart_to_js_script_rewriter: any
dependency_overrides:
  dartemis:
    path: ../dartemis
transformers:
- dart_to_js_script_rewriter